### ISSUE TITLE
There is no way to set limits for bamboo user

### ISSUE THREAD

**Issue by duddun** [afklm/bamboo#19]
There should be a way to set limits for the bamboo user via attributes, so that it automatically creates entries in a file (e.g. bamboo.conf) in /etc/security/limits.d that could look like this for example:
bamboo soft     nofile  16384
bamboo hard    nofile  32768

**Comment by ramonskie** [comment]
can you give a example of why you want to set this?

**Comment by wolf31o2** [comment]
We have plans that perform unit tests with HBase and other Java processes which open potentially thousands of file handles. To get Bamboo to function, we have to set these limits ourselves. It would be nice if the cookbook supported setting them, directly.

References:
https://github.com/caskdata/hadoop_cookbook/blob/master/attributes/default.rb#L38-L40
https://github.com/caskdata/hadoop_cookbook/blob/master/recipes/default.rb#L249-L261

**Comment by ramonskie** [comment]
so its not for the server but for the agents

**Comment by wolf31o2** [comment]
It would need to be applied to either, as the server could use a local
agent or remote agents. In Cask's case, we only use remote agents.

**Comment by ramonskie** [comment]
I will implement it in the next release

**Comment by wolf31o2** [comment]
What's gained by it being in a wrapper versus just being attribute-driven in the main cookbook? I tend to prefer keeping functionality in the main cookbook as much as possible, but making its usage data-driven, so it can be configured in the widest number of scenarios... environment, role, or wrapper.

**Comment by ramonskie** [comment]
well i don't want to bloat this bamboo cookbook
i already want to remove the backup part so that it installs a nice and clean bamboo

as i see it the best option for you is to add the limits cookbook to your run list
https://supermarket.chef.io/cookbooks/limits

**Comment by wolf31o2** [comment]
Yeah, I gave examples in my first comment.

https://issues.cask.co/browse/INFRA-4

Anyway, I'll just wrap the cookbook.
