### ISSUE TITLE
Create the home_dir or its parent before ark resource runs

### ISSUE THREAD

**Issue by patcon** [afklm/bamboo#24]
If someone wants to set the ark home_dir to be something like `/opt/atlassian/bamboo` then they can't without creating a whole wrapper cookbook to create a nest dir.

Perhaps this could be part of ark, but since perms are important, I imagine they would want that in the bamboo's application cookbook. I'll open an issue in their queue, but I suspect they'll say it goes here :)

**Comment by ramonskie** [comment]
it should create the parrent directory see https://github.com/burtlo/ark/blob/master/providers/default.rb#L36

**Comment by patcon** [comment]
Thanks for the reply, but this is about the `home_dir` resource attr, not `path`

**Comment by mvdkleijn** [comment]
@patcon Mind if I close this one until you get an answer from the ark guys? :smile:

**Comment by patcon** [comment]
sounds fair. thanks for asking :)
