### ISSUE TITLE
Make default mysql version more cross-platform

### ISSUE THREAD

**Issue by patcon** [afklm/bamboo#30]
Bamboo support 5.5 and 5.6: https://confluence.atlassian.com/display/BAMBOO/Supported+platforms

The default of 5.6 doesn't exist on some systems (like ubuntu 12.04), so might be more friendly to default to whatever the mysql library cookbook says?

https://github.com/chef-cookbooks/mysql/blob/master/libraries/helpers.rb#L430-L445

We could do this by:

``` rb
default[:bamboo][:database][:version] = nil
```

This would only go awry on old platforms that install 5.1 (unsupported)

**Comment by ramonskie** [comment]
ubuntu 12.04 is deprecated and we should not support this
but if they do want to use it with ubuntu 12.04 they can define a older version

we should focus only on supported platforms

**Comment by patcon** [comment]
10.04 is deprecated -- 12.04 is supported until almost 2018

https://wiki.ubuntu.com/LTS

**Comment by ramonskie** [comment]
https://github.com/chef-cookbooks/mysql/blob/v6.0.26/libraries/helpers.rb#L414-L432

**Comment by ojawel** [comment]
2.0.0 does not support ubuntu 12.04 anymore since ubuntu 12.04 is EOL
