### ISSUE TITLE
move to postgresql by default?

### ISSUE THREAD

**Issue by ramonskie** [afklm/bamboo#35]
the preferred database for bamboo seems to be postgresql
due to some mysql related bamboo bugs

this would creating breaking changes for ppl who are upgrading.

for now i'm just adding the ability to select postgresql

**Comment by ramonskie** [comment]
no one responded so the next major release will move to postgresql

**Comment by mvdkleijn** [comment]
:+1:

**Comment by wolf31o2** [comment]
So long as MySQL support doesn't break, I'm totally cool with it. I use MySQL already, so I can help test on that setup.

**Comment by jpmat296** [comment]
This issue should be closed, no ?

**Comment by mvdkleijn** [comment]
Yes. Default is postgresql.
