### ISSUE TITLE
latest postgresql cookbook breaks bamboo on ubuntu 14.04

### ISSUE THREAD

**Issue by ramonskie** [afklm/bamboo#38]
the latest postgresql cookbook v3.4.21 breaks on ubuntu 14.04
it installs postgresql-server 9.3 and then wants to start and initialize with 9.4
but we explicitly tell that 9.4 should be installed

this issue does not occur in v3.4.16

**Comment by ramonskie** [comment]
see
https://github.com/hw-cookbooks/postgresql/issues/302

**Comment by ojawel** [comment]
for ubuntu 14.04 and lower postgresql 9.4 is used, ubuntu 16.04 uses 9.5
