### ISSUE TITLE
Issues when running default cookbook on Ubuntu Trusty 14.04

### ISSUE THREAD

**Issue by swade1987** [afklm/bamboo#40]
I am receiving the following issue when running the cookbook

https://gist.github.com/swade1987/f4db01a88c8ee762a31d

**Comment by swade1987** [comment]
I have managed to get past the first issue, however I now get the following:

https://gist.github.com/swade1987/2d32e149319763640159

**Comment by ramonskie** [comment]
can you paste the whole lgo because it seems im missing something

**Comment by swade1987** [comment]
https://gist.github.com/swade1987/496e4a526dacbca30527

**Comment by ramonskie** [comment]
i have no idea i don't see a specific error

can you start the bamboo manually on the vm

sudo service bamboo restart

**Comment by mvdkleijn** [comment]
Also mayby paste the stacktrace: /var/chef/cache/chef-stacktrace.out

**Comment by swade1987** [comment]
output: https://gist.github.com/swade1987/4e3f278b605d5425b5ea

however, when I browse to http://ec2-54-149-109-200.us-west-2.compute.amazonaws.com/ nothing displays

**Comment by ramonskie** [comment]
can you check the bamboo logs
they are in /var/bamboo/logs/*

**Comment by swade1987** [comment]
```
root@ip-10-0-1-185:/var/chef/cache# cat chef-stacktrace.out
Generated at 2016-02-04 13:55:40 +0000
Net::HTTPServerException: 403 "Forbidden"
/opt/chef/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/http.rb:146:in `request'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/http.rb:119:in `put'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/node.rb:614:in `save'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/client.rb:524:in `save_updated_node'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/client.rb:695:in `converge_and_save'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/client.rb:271:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:261:in `block in fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:249:in `fork'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:249:in `fork_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:215:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:203:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application/client.rb:413:in `block in interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application/client.rb:403:in `loop'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application/client.rb:403:in `interval_run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application/client.rb:393:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/lib/chef/application.rb:58:in `run'
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.6.0/bin/chef-client:26:in `<top (required)>'
```

**Comment by ramonskie** [comment]
which chef client do you use?

**Comment by swade1987** [comment]
bamboo logs - https://gist.github.com/swade1987/ea572c2e1fad82e4c455

chef client - 12.6.0.1

**Comment by mvdkleijn** [comment]
One of my colleagues reported issues when using chef client 12.6.x You could try pinning the chef version to 12.4.x but I'm not sure that will resolve your issue.

Based on the 403 message I saw... Since Chef 12 has ACLs, the client needs to have permission to update its own node. If the client and the node are created simultaneously, this gets correctly set. If a new client is created for an existing node, it isn't. Is this a completely new node (& client)?

Anyway, the fix for that would be to install the knife-acl gem and then run:

```knife acl add nodes NODENAME update client NODENAME```

**Comment by swade1987** [comment]
The node is created using terraform and then provisioned using Chef. During this provisioning it downloads the chef client and executes the runlist I have set. Ideally I don't want manual workarounds as the whole idea is to have everything automated/scripted.

**Comment by mvdkleijn** [comment]
Understood. In that case the ACLs should be fine.

**Comment by swade1987** [comment]
what do you mean by ACLs?

**Comment by mvdkleijn** [comment]
I mean the ACLs / permissions on Chef server. Nice overview in the readme here: https://github.com/chef/knife-acl

**Comment by swade1987** [comment]
what so instead of using the built in chef provisioner execute these commands remotely straight onto the box?

**Comment by ramonskie** [comment]
Trybto pin your chef client in your  terraform file first and set it to 12.4

**Comment by swade1987** [comment]
Interesting suggestion, let me give that one a go.

**Comment by swade1987** [comment]
It was a lot better than before, however it gets stuck here ...

```
←[0m←[0maws_instance.bamboo-server (chef): ←[0m  * service[bamboo] action restart
←[0m←[0m
←[0m←[0maws_instance.bamboo-server (chef):     ←[32m- restart service service[bamboo]←[0m
←[0m←[0maws_instance.bamboo-server (chef): ←[0m←[0m
←[0m←[0maws_instance.bamboo-server (chef): Running handlers:←[0m
←[0m←[0maws_instance.bamboo-server (chef): [2016-02-04T16:05:36+00:00] ERROR: Running exception handlers
←[0m←[0maws_instance.bamboo-server (chef): Running handlers complete
←[0m←[0maws_instance.bamboo-server (chef): ←[0m[2016-02-04T16:05:36+00:00] ERROR: Exception handlers complete
←[0m←[0maws_instance.bamboo-server (chef): Chef Client failed. 37 resources updated in 177.135348114 seconds←[0m
←[0m←[0maws_instance.bamboo-server (chef): [2016-02-04T16:05:36+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-
stacktrace.out
←[0m←[0maws_instance.bamboo-server (chef): [2016-02-04T16:05:36+00:00] ERROR: 403 "Forbidden"
←[0m←[0maws_instance.bamboo-server (chef): [2016-02-04T16:05:36+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef
 run process exited unsuccessfully (exit code 1)
←[31mError applying plan:

1 error(s) occurred:

* Command "sudo chef-client -j \"/etc/chef/first-boot.json\" -E \"core-services\"" exited with non-zero exit status: 1
```

**Comment by ramonskie** [comment]
totally forgot about this..
is your problem solved yet?

**Comment by swade1987** [comment]
I managed to get the cookbook working, however is there a way to automate the licence?

**Comment by ramonskie** [comment]
do you know what the issues was?

and no there is no way in bamboo to set the license at the moment :(
i requested this at atlassian but i don't think they are ever going to fix this
they arranged it for stash/bitbucket though

**Comment by swade1987** [comment]
Fair enough, additionally is their an easy way to make sure a new agent is associated with the server, in an automated fashion?

Regards

Steve
------------------------------------
Steven Wade
Principal Consultant
Steven Wade Consulting Ltd
steven@stevenwade.co.uk<mailto:steven@stevenwade.co.uk>
uk.linkedin.com/in/stevendavidwade/<http://uk.linkedin.com/in/stevendavidwade/>

On 19 Feb 2016, at 09:34, Ramon Makkelie <notifications@github.com<mailto:notifications@github.com>> wrote:


do you know what the issues was?

and no there is no way in bamboo to set the license at the moment :(
i requested this at atlassian but i don't think they are ever going to fix this
they arranged it for stash/bitbucket though

**Comment by ramonskie** [comment]
yes you can just create a new role with bamboo::agent
and set it to a new vm

and the best option to achieve this is with terraform ofcourse

**Comment by swade1987** [comment]
But how does the agent know to associate itself with the server?

Of course, Terraform is the only option nowadays ;)

Regards

Steve
------------------------------------
Steven Wade
Principal Consultant
Steven Wade Consulting Ltd
steven@stevenwade.co.uk<mailto:steven@stevenwade.co.uk>
uk.linkedin.com/in/stevendavidwade/<http://uk.linkedin.com/in/stevendavidwade/>

On 19 Feb 2016, at 09:41, Ramon Makkelie <notifications@github.com<mailto:notifications@github.com>> wrote:


yes you can just create a new role with bamboo::agent
and set it to a new vm

and the best option to achieve this is with terraform ofcourse

**Comment by ramonskie** [comment]
see end of line https://github.com/ramonskie/bamboo/blob/master/recipes/agent.rb#L60

**Comment by swade1987** [comment]
This is for a linux agent, unfortunately I need to have windows agents as we are a .NET house.

Regards

Steve
------------------------------------
Steven Wade
Principal Consultant
Steven Wade Consulting Ltd
steven@stevenwade.co.uk<mailto:steven@stevenwade.co.uk>
uk.linkedin.com/in/stevendavidwade/<http://uk.linkedin.com/in/stevendavidwade/>

On 19 Feb 2016, at 09:46, Ramon Makkelie <notifications@github.com<mailto:notifications@github.com>> wrote:


see end of line https://github.com/ramonskie/bamboo/blob/master/recipes/agent.rb#L60

**Comment by ramonskie** [comment]
i did not created a windows agent
because we do not use windows
you can however create a pull request :+1:

**Comment by mvdkleijn** [comment]
Closing this issue as it appears resolved.
@swade1987 You're welcome to create a PR for a Windows agent in future. :smile:
