### ISSUE TITLE
Unable to login in Bamboo 5.13+

### ISSUE THREAD

**Issue by dsantos-atlassian** [afklm/bamboo#52]
Due to recent changes in <Bamboo_Install>/atlassian-bamboo/WEB-INF/classes/seraph-config.xml for Bamboo 5.13.0.1, the recipe is failing after the installation.
When you logout at first time you are not able to login back and the following stack track is thrown in the logs:

> 2016-09-16 16:25:27,070 INFO [http-nio-8085-exec-11] [AccessLogFilter] 192.168.10.144 GET http://192.168.10.144:8085/bamboo/userlogin!default.action?os_destination=/start.action 413355kb
> 2016-09-16 16:25:33,262 WARN [http-nio-8085-exec-11] [Dispatcher] Could not find action or result: /bamboo/userlogin!default.action?os_destination=/start.action
> Method default for action userlogin is not allowed! - [unknown location]
>         at com.opensymphony.xwork2.DefaultActionProxy.prepare(DefaultActionProxy.java:200)
>         at org.apache.struts2.factory.StrutsActionProxy.prepare(StrutsActionProxy.java:63)
>         at org.apache.struts2.factory.StrutsActionProxyFactory.createActionProxy(StrutsActionProxyFactory.java:37)
>         at com.opensymphony.xwork2.DefaultActionProxyFactory.createActionProxy(DefaultActionProxyFactory.java:58)
>         at org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:548)

**The following changes seems to fix the problem:**
**Change the references of:**
`<param-value>/userlogin!default.action?os_destination=${originalurl}</param-value>`
**to:**
`<param-value>/userlogin!doDefault.action?os_destination=${originalurl}</param-value>`

**Comment by cgrout** [comment]
For anyone else's benefit... Until this is resolved, an easy workaround is to delete the included resource and simply substitute your own updated version.

i.e.
```#!ruby
include_recipe 'bamboo::server'
delete_resource(:template, 'seraph-config.xml')

cookbook_file '/opt/bamboo/atlassian-bamboo/WEB-INF/classes/seraph-config.xml' do
  source 'seraph-config.xml'
  owner 'bamboo'
  group 'bamboo'
  mode 00644
end
```

**Comment by jpmat296** [comment]
Is there still something pending to close this issue ?

**Comment by ojawel** [comment]
nope
